alert("Hello");
alert(1+2+3);
[1,2].forEach(alert);
alert("some code");
"use stict";
prompt("Hello",'150');
let Hello = "Hello World";
let message;
message = Hello;
document.write(message);
let str1 = "Hello";
let str2 = "To";
let welcome = `${str1} ${str2} Eveyone`;
alert(welcome);